### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by arsium** [Virgula0/Wifi-Inspector#1]
I tried this on the lastest windows 10  and it seems not to work

**Comment by Virgula0** [comment]
Hello, thanks to having noticed me. Tested on Windows 10 Home Version 10.0.18362 N/D build 18362 just now and it still works. Could you please be more detailed about your Windows version and the problem you have with the program (error or any kind of detailed explanation)? Thank You.

**Comment by arsium** [comment]
Lastest Windows 10 1903 V 18362.592 Pro in french

**Comment by Virgula0** [comment]
Thank you , but can you please describe what error do you get with the program since you're saying that it doesn't work? Describe the error linking some screen-shots too , if you can.

**Comment by arsium** [comment]
I just don't get any devices in listview

**Comment by Virgula0** [comment]
First of all, are you sure your pc was connected to any wireless network before? If not, it's normal that nothing is shown.
As second, try to run the program with administrative privileges and check if something changes, give me also the output of this command executed on a terminal (try with admin privileges first and without then, give me the output):
`netsh wlan show profiles`

**Comment by Virgula0** [comment]
I assume the software is not affected by any other bug since the users didn't answer over 11 days.  "the problem" described by him is not a problem if a pc was not connected to any other protected network before.

**Comment by arsium** [comment]
Hello dear , sorry to answer later. I'm connected and i tried to run as admin but nothing appened in the list where the ssid and my passwords have to appear.
